import { ConversationDetail } from "../types/conversation";

export const conversationDetails: { [key: string]: ConversationDetail } = {
  '1': {
    id: '1',
    customerName: 'Sarah Johnson',
    lastMessage: "Besoin d'aide avec mon ordre principal",
    timestamp: 'Il y a 5 minutes',
    status: 'active',
    channel: 'WhatsApp',
    customerEmail: 'sarah.johnson@email.com',
    customerPhone: '+33 6 12 34 56 78',
    orderNumber: 'CMD-2024-00123',
    messages: [
      {
        id: '1',
        text: "Bonjour, j'ai besoin d'aide avec ma commande #CMD-2024-00123",
        timestamp: '14:30',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: 'Je suis votre agent principal, comment puis-je vous aider ?',
        timestamp: '14:32',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "Le produit n'est pas arrivé alors que la livraison était prévue pour hier",
        timestamp: '14:33',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '4',
        text: 'Je vérifie immédiatement le statut de votre livraison et vous tiens informé',
        timestamp: '14:35',
        sender: 'agent',
        type: 'text',
      },
    ],
  },
  '2': {
    id: '2',
    customerName: 'Mike Thompson',
    lastMessage: 'Problème avec la livraison principale',
    timestamp: 'Il y a 10 minutes',
    status: 'active',
    channel: 'Messenger',
    customerEmail: 'mike.thompson@email.com',
    customerPhone: '+33 6 98 76 54 32',
    orderNumber: 'CMD-2024-00124',
    messages: [
      {
        id: '1',
        text: "Ma commande n'est toujours pas arrivée alors qu'elle devait être livrée hier",
        timestamp: '14:25',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: "Je vais vérifier l'état de votre livraison immédiatement. Pouvez-vous me donner votre numéro de commande ?",
        timestamp: '14:28',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "C'est la commande #CMD-2024-00124",
        timestamp: '14:29',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
  '3': {
    id: '3',
    customerName: 'Emma Davis',
    lastMessage: 'Question technique sur le produit',
    timestamp: 'Il y a 1 heure',
    status: 'inactive',
    channel: 'Messenger',
    customerEmail: 'emma.davis@email.com',
    customerPhone: '+33 6 45 67 89 10',
    orderNumber: 'CMD-2024-00125',
    messages: [
      {
        id: '1',
        text: "J'ai un problème technique avec mon appareil",
        timestamp: '13:30',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: 'Je suis votre expert technique, décrivez-moi le problème en détail',
        timestamp: '13:35',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "L'écran reste noir même quand je l'allume",
        timestamp: '13:36',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '4',
        text: 'Essayez de maintenir le bouton power enfoncé pendant 10 secondes puis relâchez',
        timestamp: '13:38',
        sender: 'agent',
        type: 'text',
      },
    ],
  },
  '4': {
    id: '4',
    customerName: 'John Smith',
    lastMessage: 'Support technique urgent',
    timestamp: 'Il y a 2 heures',
    status: 'active',
    channel: 'WhatsApp',
    customerEmail: 'john.smith@email.com',
    customerPhone: '+33 6 11 22 33 44',
    orderNumber: 'CMD-2024-00126',
    messages: [
      {
        id: '1',
        text: 'Mon équipement ne fonctionne plus du tout',
        timestamp: '12:30',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: "Support technique à votre écoute, quelle est la référence de l'équipement ?",
        timestamp: '12:35',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "C'est le modèle XT-2000, série 4587",
        timestamp: '12:36',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
  '5': {
    id: '5',
    customerName: 'Lisa Brown',
    lastMessage: 'Question commerciale',
    timestamp: 'Il y a 3 heures',
    status: 'inactive',
    channel: 'WhatsApp',
    customerEmail: 'lisa.brown@email.com',
    customerPhone: '+33 6 55 66 77 88',
    orderNumber: 'QUO-2024-00127',
    messages: [
      {
        id: '1',
        text: 'Je souhaite obtenir des informations commerciales sur vos nouveaux produits',
        timestamp: '11:30',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: 'Service commercial à votre service, que souhaitez-vous savoir exactement ?',
        timestamp: '11:35',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: 'Quelles sont les caractéristiques du modèle premium ?',
        timestamp: '11:36',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
  '6': {
    id: '6',
    customerName: 'David Wilson',
    lastMessage: 'Demande de devis commercial',
    timestamp: 'Il y a 4 heures',
    status: 'active',
    channel: 'Email',
    customerEmail: 'david.wilson@email.com',
    customerPhone: '+33 6 99 88 77 66',
    orderNumber: 'QUO-2024-00128',
    messages: [
      {
        id: '1',
        text: 'Je voudrais un devis pour vos services entreprise',
        timestamp: '10:30',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: "Je vous prépare un devis personnalisé immédiatement. Combien d'utilisateurs ?",
        timestamp: '10:35',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "Nous sommes 25 utilisateurs dans l'entreprise",
        timestamp: '10:36',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
  '7': {
    id: '7',
    customerName: 'Sophie Martin',
    lastMessage: 'Support premium prioritaire',
    timestamp: 'Il y a 30 minutes',
    status: 'active',
    channel: 'WhatsApp',
    customerEmail: 'sophie.martin@email.com',
    customerPhone: '+33 6 44 55 66 77',
    orderNumber: 'CMD-2024-00129',
    messages: [
      {
        id: '1',
        text: 'Support premium - demande urgente pour un problème critique',
        timestamp: '14:00',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: 'Support premium à votre écoute, quelle est votre demande prioritaire ?',
        timestamp: '14:05',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: "Notre système de production est arrêté à cause d'un bug",
        timestamp: '14:06',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
  '8': {
    id: '8',
    customerName: 'Robert Garcia',
    lastMessage: 'Question premium VIP',
    timestamp: 'Il y a 1 heure',
    status: 'active',
    channel: 'Messenger',
    customerEmail: 'robert.garcia@email.com',
    customerPhone: '+33 6 33 22 11 00',
    orderNumber: 'CMD-2024-00130',
    messages: [
      {
        id: '1',
        text: "J'ai une question VIP concernant mon abonnement premium",
        timestamp: '13:00',
        sender: 'customer',
        type: 'text',
      },
      {
        id: '2',
        text: "Service premium VIP, je m'occupe personnellement de votre demande",
        timestamp: '13:05',
        sender: 'agent',
        type: 'text',
      },
      {
        id: '3',
        text: 'Je souhaite étendre la couverture à nos filiales européennes',
        timestamp: '13:06',
        sender: 'customer',
        type: 'text',
      },
    ],
  },
};